### ISSUE TITLE
Does this support abtract states for ui-router ?

### ISSUE THREAD

**Issue by binarysqueeze** [castillo-io/angular-css#25]
Hi there,

I was wanting a way to include a certain CSS file (which is dynamic) on each and every state. I was thinking of doing this via an abstract state and having all other states use the abstract.

Does this support abstract states?

The css I need to include on every page would be available in a variable but I just can't insert it onto the page as it changes depending on certain this.

Is there support for this ?

**Comment by kenny-f** [comment]
From digging into the source and testing on my project it currently does not support abstract states.

This would be a killer feature as I suspect most people will have a abstract states that define a base layout that other child states will populate the ui-view.

I'm currently working on a project with an abstract base 'frontend' state (home, login, register pages) and an abstract base 'dashboard' state. It would be great if I could define a set of css files for both abstract states whenever a child state is instantiated. 

However, I do not see an easy way to go **up** the state tree.

**Comment by alexandercastillo** [comment]
Hi @ianjohnmadrid and @kenny-f 

I can see the value of adding this as a feature. I'm going to look into it and see how we can approach this.

Thanks!

**Comment by ianjohnmadrid** [comment]
Great news. Thanks

**Comment by kenny-f** [comment]
Thanks!

My current workaround is to have a controller on the base abstract state and load the css from there.

**Comment by alexandercastillo** [comment]
That is a good workaround for the time being. I'll still look into it so we can do this properly.

**Comment by freshfelicio** [comment]
I have an abstract state that contains a navbar, a ui-view and a footer. It is abstract because there should always be content inside the ui-view. But the navbar has its own stylesheet that I need to load... please add this feature.

**Comment by DrakeWitt** [comment]
What is that status of this feature?

**Comment by heston** [comment]
Looks like this PR added support for inheritance via abstract states when using the 'data' property: https://github.com/castillo-io/angular-css/pull/35

**Comment by alexcastillo** [comment]
I believe this was resolved in #35.
Releasing soon.

**Comment by alexcastillo** [comment]
Fixed in v1.0.8
