### ISSUE TITLE
css inheritance for child states for ui-router (non abstract)

### ISSUE THREAD

**Issue by yahyaKacem** [castillo-io/angular-css#28]
Hi, is it possible to define nested states with ui-router and assign a stylesheet to a parent state that will be inherit for all child states?
Something like this:
- profile: profile.css.
- profile.about: about.css.
- profile.friends: friends.css.

Where profile.about and profile.friends states both will not reload the profile.css file since it was already loaded for the profile state?
what I found happen is that only the child state style file is loaded!
is that the intended behaviour, or there's something I'm missing?
here's a [plunker](http://plnkr.co/edit/Jx9ai6?p=preview) with examples, thanks in advance.
# update:

when using the controller with the routes configurations the parent stylesheet gets loaded after the child stylesheet which ruin the overrides in the child state, this also happen when using only the controllers without the states configuration, also the link tags in the head gets inserted in the wrong order they should be reversed.

**Comment by simonefalcini** [comment]
Is it possible to fix this?

**Comment by DrakeWitt** [comment]
+1

**Comment by mplushnikov** [comment]
We are at the same point and also need support for nested states:) Can you merge/apply changes from bbuhler? It looks like a possible solution:)
