### ISSUE TITLE
Its not working in IE8

### ISSUE THREAD

**Issue by BhagyashriJ** [castillo-io/angular-css#39]
In IE8 page is not loading if i add it

**Comment by alexandercastillo** [comment]
Hi @BhagyashriJ 

Unfortunately, we do not support IE8 since AngularJS 1.3 has dropped support for IE8.
https://docs.angularjs.org/guide/ie

If we get enough people to +1, I can add IE8 support to the backlog.

**Comment by think2011** [comment]
+1

**Comment by tommas3210** [comment]
+1

**Comment by think2011** [comment]
Let's drop IE8 : (
