### ISSUE TITLE
$logProvider.debugEnabled false is overridden by app module

### ISSUE THREAD

**Issue by MokoJumbie** [castillo-io/angular-css#41]
When the angular-css module is included in an app, the module's $logProvider.debugEnabled setting is overridden by the parent app's setting as it seems impossible to make the angular-css module have a distinct config phase. This makes for a significant amount of console noise.

Can the debugging be disabled in a way that leaves debugging enabled for the parent app? Perhaps remove the debug lines entirely as part of the build process, building to a dist folder?

Or am I seeing some weird behaviour that nobody else is seeing?

I'm using Angular 1.4.5

**Comment by leafymind** [comment]
I also running into that. :-/

**Comment by alexcastillo** [comment]
I believe this was resolved on #47 
Releasing soon.

**Comment by alexcastillo** [comment]
Fixed in v1.0.8
