### ISSUE TITLE
link.apply is not a function

### ISSUE THREAD

**Issue by heekyu** [castillo-io/angular-css#43]
<img width="291" alt="2015-09-28 8 39 21" src="https://cloud.githubusercontent.com/assets/5581863/10134487/14441ea2-6621-11e5-97e6-73534723ed4c.png">

I added angular-css.js and 
css included in directive works fine.
but "link.apply is not a function" error occured.

**Comment by spirospolitis** [comment]
Had the same issue which was resolved when i removed the

```javascript
link: {
   pre: function(scope, element, attributes) {
      ...
   },
   post: function(scope, element, attributes) {
      ...
   }
}
```
definition from my directive.

Hope it helps in tracking down the issue.

Thank you for this great little component :+1:
