### ISSUE TITLE
Release 1.0.8

### ISSUE THREAD

**Issue by wingedfox** [castillo-io/angular-css#56]
Hi,

Angular 1.5.0 has been released. Please release angular-css 1.0.8, as long as master contains the angular 1.5 compatibility fix.

**Comment by KristjanTammekivi** [comment]
Yes, please. Version 1.0.7 doesn't have the proper module.exports for use with Node.js (#58)

**Comment by alexcastillo** [comment]
Fixed in v1.0.8
