### ISSUE TITLE
Can this be used in angular 2?

### ISSUE THREAD

**Issue by ozexpert** [castillo-io/angular-css#59]
just curious. thanks.

**Comment by Zaithe** [comment]
I am curious of this as well!

**Comment by alexcastillo** [comment]
Angular 2 comes with a similar feature out of the box. It's called 'styleUrls' and it looks like this:

```js
@Component({
  selector: 'contributors',
  templateUrl: 'app/components/contributors/contributors.html',
  styleUrls: ['app/components/contributors/contributors.css'],
  directives: [],
})
```

As far as I know, it doesn't have all the features that AngularCSS has, like preloading, weight, ect.
I'll be exploring this more in depth soon in Angular 2 and maybe we can contribute to it :)
