### ISSUE TITLE
Error: [orderBy:notarray] Expected array but received: 0

### ISSUE THREAD

**Issue by caelum777** [castillo-io/angular-css#60]
Using Angular 1.5.0 and $routeProvider to inject the css like this:

```.when('/profile/:memberId', {
    templateUrl: 'views/profile.html',
    controller: 'ProfileCtrl',
    css: { href: 'assets/css/profile.css', preload: true },
    controllerAs: 'profile'
})```

Get an error that says: "Error: [orderBy:notarray] Expected array but received: 0"

**Comment by rpedroni** [comment]
Started getting this error when I migrated my code base into another project. Mine complains about orderBy:notarray instead.

**Comment by jorgemarcondes** [comment]
Same happens with me, please try to fix it.

maybe here:
ngRepeat: stylesheet in stylesheets track by $index | orderBy: 'weight'

**Comment by darleendenno** [comment]
Same here! I double checked my dependencies and tried a few different ways of doing this, but still receive the same error. What's going on?

**Comment by harmoniemand** [comment]
as a workaround you could search for this line
`var template = '<link ng-repeat="stylesheet in stylesheets track by $index | orderBy: \'weight\' " rel="{{ stylesheet.rel }}" type="{{ stylesheet.type }}" ng-href="{{ stylesheet.href }}" ng-attr-media="{{ stylesheet.media }}">';
`

and remove the 
>  | orderBy: \'weight\'

**Comment by cwx0046** [comment]
Does anyone received this error after use  `angular-cookies`?
In a  new project I didn't met this error at first, but add `angular-cookies` made this happen.

**Comment by danielcaldas** [comment]
Same thing here... Using Angular 1.5.0 and getting this:
angular.js:13424 Error: [orderBy:notarray]

**Comment by charlottefranklin** [comment]
Same here.

**Comment by alexcastillo** [comment]
Thank you for the feedback, everyone.
I'm working on a fix.

**Comment by alexcastillo** [comment]
Fixed in v1.0.8

**Comment by charlottefranklin** [comment]
Thanks for the fix!
Make sure to update the module name from `door3.css` to `angularCSS`.

**Comment by harmoniemand** [comment]
May you should open a separate issue for this
