### ISSUE TITLE
Update the bower package

### ISSUE THREAD

**Issue by windht** [castillo-io/angular-css#64]
Please update the bower~

Your module is amazing!

**Comment by windht** [comment]
And please also fix the release version name. Currently it is 0.1.8, I think you mean 1.0.8.

**Comment by alexcastillo** [comment]
Hi @windht 

I updated bower yesterday when I released v0.1.8
Try `bower info angular-css`

Also, the version is correct. We are not still v1, getting there though. 

Thanks!

**Comment by oopsyummy** [comment]
I do think bower will recognize and update automatically if the tag is "1.0.8" since the last tag is "1.0.7". Never mind!
